name: DEV - Fauna DB Migrations

on:
  push:
    branches: [development]

jobs:
  apply-dev-db-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      - name: Apply DB Migrations in DEV DB
        run: yarn apply-db-migrations --legacy
        env:
          FAUNADB_DOMAIN: ${{ secrets.FAUNADB_DOMAIN }}
          FAUNA_ADMIN_KEY: ${{ secrets.FAUNA_ADMIN_KEY_DEV }}
