name: Lighthouse
on: [push]
jobs:
  lighthouse-ci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile && yarn global add @lhci/cli
      - run: echo -e "NEXT_PUBLIC_NETWORK=avm\nNEXT_PUBLIC_OG_IMAGE_URL=https://og-image.ideamarket.io\nMIX_PANEL_KEY=bdc8707c5ca435eebe1eb76c4a9d85d5" > .env.local
      - run: yarn build
      - run: lhci autorun --config=.github/lighthouse/lighthouserc-desktop.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - run: lhci autorun --config=.github/lighthouse/lighthouserc-mobile.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
